# Use the official Python image
FROM python:3.12.6-slim

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies (e.g., for OpenCV)
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

# Copy project files to the container
COPY . /app

# Install Python dependencies
RUN pip install --default-timeout=10000 -r requirements.txt

# Specify the command to run your application
# CMD ["python", "main_docker.py"]
CMD ["python", "-u", "main_docker.py"]

# docker build -t yolov3-python-v3 .
# docker run --privileged -d -v D:\Bryan_Workspace\bus-people-monitoring\yolov3-python\images:/app/images yolov3-python-v3
# docker logs -f 1cf8f4728055
# docker save -o yolov3-python-v4.tar yolov3-python-v4